# Generated by Django 5.2 on 2025-05-02 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animais',
            old_name='data_da_criacao',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='animais',
            old_name='raca',
            new_name='petBreed',
        ),
        migrations.RenameField(
            model_name='animais',
            old_name='Nome_do_pet',
            new_name='petName',
        ),
        migrations.RenameField(
            model_name='animais',
            old_name='foto_pet',
            new_name='petPhotoUrl',
        ),
        migrations.RenameField(
            model_name='animais',
            old_name='tipo_de_pet',
            new_name='petType',
        ),
    ]
