# Generated by Django 5.2 on 2025-05-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_do_pet', models.CharField(max_length=30)),
                ('tipo_de_pet', models.CharField(max_length=40)),
                ('raca', models.CharField(max_length=40)),
                ('foto_pet', models.ImageField(upload_to='images')),
                ('data_da_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'pets',
                'ordering': ['id'],
            },
        ),
    ]
